image:
  file: .gitpod.Dockerfile
# Command to start on workspace startup (optional)
tasks:
  - command: hugo server -D
# Ports to expose on workspace startup (optional)
ports:
  - port: 1313
    onOpen: open-browser
